title: Inpsyde Assets

description: >-
  Inpsyde Assets is a Composer package (not a plugin) that allows to deal with scripts and styles in a WordPress site.
baseurl: /assets/ # Use GitHub repo name.

# Aux links for the upper right navigation
aux_links:
  GitHub:
    - https://github.com/inpsyde/assets

# Footer "Edit this page on GitHub" link text
gh_edit_repository: https://github.com/inpsyde/assets # the GitHub URL for the repo
# TODO: Change to `master` when merging
gh_edit_branch: jekyll # the default branch of the repo
gh_edit_source: docs # the directory containing the docs

# Everything above is repo specific.

###############################################################

# Everything below should be copy and pasted into package repos

## TODO: Change to inpsyde/jekyll-inpsyde-theme
remote_theme: pmarsceill/just-the-docs

###############################################################

# Everything below should be copy and pasted into package repos
# To be replaced by theme's `_config.yml` when GitHub Pages supports Jekyll v4.

logo: /assets/images/inpsyde-rgb-flat-2.svg
favicon: /assets/images/favicon.png

gh_edit_link: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

permalink: pretty
