name: PHP-QA

on: [ push ]

jobs:
  lint-php:
    uses: inpsyde/reusable-workflows/.github/workflows/lint-php.yml@main
    strategy:
      matrix:
        php: [ '7.4', '8.0', '8.1', '8.2' ]
        composer-args: ''
        include:
          - php-version: '7.4'
            composer-args: '--ignore-platform-req=php'
          - php-version: '8.0'
            composer-args: '--ignore-platform-req=php'
    with:
      PHP_VERSION: ${{ matrix.php }}
      COMPOSER_ARGS: ${{ matrix.composer-args }}
  coding-standards-analysis-php:
    uses: inpsyde/reusable-workflows/.github/workflows/coding-standards-php.yml@main
    with:
      PHPCS_ARGS: '--report=summary'
      PHP_VERSION: '8.1'
  static-code-analysis-php:
    uses: inpsyde/reusable-workflows/.github/workflows/static-analysis-php.yml@main
    with:
      PHP_VERSION: '8.1'
  tests-unit-php:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    strategy:
      matrix:
        php-versions: [ '7.4', '8.0', '8.1', '8.2' ]
        composer-args: ''
        include:
          - php-version: '7.4'
            composer-args: '--ignore-platform-req=php'
          - php-version: '8.0'
            composer-args: '--ignore-platform-req=php'
    steps:
      - uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest -a ${{ matrix.composer-version }}

      - name: Run unit tests
        run: composer tests:codecov

      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: unittests
          verbose: true
