name: Testing

on: [push]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: pcov

      - name: Check syntax error in sources
        run: find ./src/ ./tests/ -type f -name '*.php' -print0 | xargs -0 -L 1 -P 4 -- php -l

      - name: Install dependencies
        run: composer install -q -n -a --no-progress --prefer-dist

      - name: Run PHPCS
        run: composer cs

      - name: Run PSALM
        run: composer psalm

  tests:
    runs-on: ubuntu-latest
    needs: quality
    strategy:
      matrix:
        php-versions: ['7.2', '7.3', '7.4', '8.0', '8.1']

    steps:
    - uses: actions/checkout@v1

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        coverage: pcov

    - name: Install dependencies
      run: composer install -q -n -a --no-progress --prefer-dist

    - name: Run PHPUNIT
      run: composer tests:codecov
      
    - uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        flags: unittests
        verbose: true
